<#
.SYNOPSIS
  Register this project's fusion_scripts/ with Fusion 360.

.DESCRIPTION
  Fusion only lists scripts that live under its own API\Scripts folder, one
  folder per script, each with a .manifest beside it. Copying the repo files
  there would fork them: you would edit one copy and run the other.

  So this installs SHIMS instead. Each shim is a three-line script that puts
  fusion_scripts/ on sys.path and calls the real module, reloading it first.
  Two consequences worth knowing:

    - git stays the single source of truth. The shims hold no logic.
    - editing a repo script and re-running it in Fusion picks up the change
      immediately. No Fusion restart, no re-install.

  Idempotent. Re-run it after adding a new script to fusion_scripts/.

.EXAMPLE
  .\install-fusion-scripts.ps1
  .\install-fusion-scripts.ps1 -WhatIf
  .\install-fusion-scripts.ps1 -Uninstall
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    # Fusion's API folder. The default is where Fusion puts it on Windows.
    [string]$FusionApi = (Join-Path $env:APPDATA 'Autodesk\Autodesk Fusion 360\API'),
    # Prefix on the installed names, so they sort together in Fusion's list.
    [string]$Prefix = 'frame_',
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$repoScripts = Join-Path $PSScriptRoot 'fusion_scripts'
if (-not (Test-Path $repoScripts)) { throw "No fusion_scripts folder beside this script ($repoScripts)" }

$scriptsDir = Join-Path $FusionApi 'Scripts'
if (-not (Test-Path $FusionApi)) {
    throw "Fusion API folder not found: $FusionApi`nOpen Fusion once, or pass -FusionApi <path>."
}
if (-not (Test-Path $scriptsDir)) { New-Item -ItemType Directory $scriptsDir | Out-Null }

# Files starting with _ are libraries, not runnable scripts. Fusion decides by
# the presence of run(context); we decide by the same convention _common uses.
$modules = Get-ChildItem $repoScripts -Filter *.py |
    Where-Object { -not $_.Name.StartsWith('_') } |
    Sort-Object Name

if (-not $modules) { throw "No runnable scripts in $repoScripts" }

$manifest = @{
    autodeskProduct = 'Fusion360'
    type            = 'script'
    author          = ''
    description     = @{ '' = 'drone-wood-frame: runs from the git repo, not from this folder' }
    supportedOS     = 'windows|mac'
    editEnabled     = $true
} | ConvertTo-Json -Depth 4

$installed = @()
$removed = @()

foreach ($module in $modules) {
    $name = $Prefix + $module.BaseName
    $dest = Join-Path $scriptsDir $name

    if ($Uninstall) {
        if (Test-Path $dest) {
            if ($PSCmdlet.ShouldProcess($dest, 'Remove shim')) {
                Remove-Item $dest -Recurse -Force
            }
            $removed += $name
        }
        continue
    }

    # Refuse to clobber something that is not one of ours.
    $shimPath = Join-Path $dest "$name.py"
    if ((Test-Path $shimPath) -and -not ((Get-Content $shimPath -Raw) -match 'drone-wood-frame shim')) {
        Write-Warning "$shimPath exists and was not written by this installer - skipping"
        continue
    }

    if (-not (Test-Path $dest)) {
        if ($PSCmdlet.ShouldProcess($dest, 'Create script folder')) {
            New-Item -ItemType Directory $dest | Out-Null
        }
    }

    $shim = @"
# drone-wood-frame shim - GENERATED by install-fusion-scripts.ps1. Do not edit.
# The real script is:
#   $($module.FullName)
# Edit that file; this one only forwards to it. Re-running the script in Fusion
# reloads the repo module, so changes take effect without restarting Fusion.
import importlib
import os
import sys

REPO_SCRIPTS = r"$repoScripts"
MODULE = "$($module.BaseName)"

if REPO_SCRIPTS not in sys.path:
    sys.path.insert(0, REPO_SCRIPTS)


def _reload_repo_modules(skip):
    """Pick up edits without restarting Fusion. _common first: the others do
    `from _common import ...`, so they must be reloaded after it to rebind."""
    loaded = []
    for name, module in list(sys.modules.items()):
        path = getattr(module, "__file__", None)
        if not path:
            continue
        if os.path.dirname(os.path.abspath(path)).lower() == REPO_SCRIPTS.lower():
            loaded.append((name, module))

    for name, module in loaded:
        if name == "_common":
            importlib.reload(module)
    for name, module in loaded:
        if name not in ("_common", skip):
            importlib.reload(module)


def run(context):
    _reload_repo_modules(skip=MODULE)
    module = importlib.import_module(MODULE)
    importlib.reload(module)
    module.run(context)
"@

    if ($PSCmdlet.ShouldProcess($shimPath, 'Write shim')) {
        Set-Content -Path $shimPath -Value $shim -Encoding utf8
        Set-Content -Path (Join-Path $dest "$name.manifest") -Value $manifest -Encoding utf8
    }
    $installed += $name
}

if ($Uninstall) {
    if ($removed) { "Removed $($removed.Count):"; $removed | ForEach-Object { "  $_" } }
    else { 'Nothing to remove.' }
    return
}

"Installed $($installed.Count) script(s) into:"
"  $scriptsDir"
''
$installed | ForEach-Object { "  $_" }
''
'In Fusion:  Utilities -> ADD-INS (Shift+S) -> Scripts tab.'
'They appear by the names above - no need for the green + button.'
''
'Run them in this order:'
'  frame_sync_params -> frame_hole_pattern -> frame_nest_parts'
'  -> frame_mass_check -> frame_export_dxf'
''
'First, from a terminal in the repo:  frame fusion -o'
